#!/usr/bin/env python3
"""Turn monogram-bitmap.json into src/font.h.

Run by hand, output committed, exactly like the device tree: the JSON is the
source of record and the header is what ships. Nothing in the build depends on
python being installed.

    tools/mkfont.py

monogram's own layout is one integer per row, twelve rows per glyph, bit 0 at
the *left*. That is kept as-is rather than transposed into columns like the
5x7 font it replaces - a transform in a generator is a transform that has to
be reasoned about every time the output looks wrong.

Only ASCII 32..126 is taken, plus seven symbols the UI actually uses, mapped
into the control range so they can sit in ordinary C string literals. The full
390 glyphs would cost a codepoint lookup on every character drawn, to render
scripts nothing on this machine can produce.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Control code -> the character in the JSON. \x00 stays blank so that an
# out-of-range byte draws nothing rather than garbage.
EXTRA = {
    1: ('↑', 'up arrow'),
    2: ('↓', 'down arrow'),
    3: ('←', 'left arrow'),
    4: ('→', 'right arrow'),
    5: ('…', 'ellipsis'),
    6: ('—', 'em dash'),
    7: ('’', 'right quote'),
}

ROWS = 12
SLOTS = 128


def main():
    src = json.load(open(os.path.join(ROOT, 'monogram-bitmap.json')))

    glyph = [[0] * ROWS for _ in range(SLOTS)]
    label = [''] * SLOTS

    for code, (ch, name) in EXTRA.items():
        if ch not in src:
            raise SystemExit('missing %s in the font data' % name)
        glyph[code] = src[ch]
        label[code] = name

    for code in range(32, 127):
        ch = chr(code)
        if ch not in src:
            raise SystemExit('missing %r in the font data' % ch)
        glyph[code] = src[ch]
        label[code] = ch if ch != '\\' else '\\\\'

    for g in glyph:
        if len(g) != ROWS:
            raise SystemExit('a glyph is not %d rows' % ROWS)
        if any(r >> 8 for r in g):
            raise SystemExit('a glyph row does not fit in a byte')

    # Ink width: the highest bit any row of the glyph sets. Space is zero and
    # stays zero, which is what makes trailing-space trimming come out right.
    width = [max((r.bit_length() for r in g), default=0) for g in glyph]
    advance = max(width) + 1

    # The rows ASCII actually inks. The cell has three empty rows of ascender
    # space on top, so a caller that lines glyphs up by cell lines them up
    # three rows lower than it looks. Emitted so that nobody has to measure it
    # off a screenshot again.
    inked = [i for i in range(ROWS)
             if any(glyph[c][i] for c in range(32, 127))]
    ink_top, ink_bot = min(inked), max(inked)

    out = ['/* pid351 - the monogram font, 12 rows per glyph, bit 0 at the left.',
           ' *',
           ' * GENERATED by tools/mkfont.py from monogram-bitmap.json. Do not edit:',
           ' * edit the JSON and re-run the generator.',
           ' *',
           ' * ASCII 32..126 at their own indices, so a C string indexes straight in,',
           ' * plus seven symbols in the control range that ordinary string literals can',
           ' * carry: \\x01 up, \\x02 down, \\x03 left, \\x04 right, \\x05 ellipsis,',
           ' * \\x06 em dash, \\x07 apostrophe. Index 0 is blank, so a byte outside the',
           ' * table draws nothing rather than garbage.',
           ' */',
           '#ifndef FONT_DATA_H',
           '#define FONT_DATA_H',
           '',
           '#define FONT_ROWS    %d' % ROWS,
           '#define FONT_MAX_W   %d' % max(width),
           '#define FONT_SLOTS   %d' % SLOTS,
           '/* The rows ASCII inks, within the %d row cell: everything above' % ROWS,
           ' * FONT_INK_TOP is ascender space no glyph uses. Line text up on the ink',
           ' * and it sits where the eye expects; line it up on the cell and it does',
           ' * not. */',
           '#define FONT_INK_TOP %d' % ink_top,
           '#define FONT_INK_H   %d' % (ink_bot - ink_top + 1),
           '',
           'static const unsigned char font_row[FONT_SLOTS][FONT_ROWS] = {']

    for code in range(SLOTS):
        rows = ', '.join('0x%02X' % r for r in glyph[code])
        note = ' /* %s */' % label[code] if label[code] else ''
        out.append('    { %s },%s' % (rows, note))
    out.append('};')
    out.append('')
    out.append('/* Ink width, not cell width: the space is 0 and the narrow glyphs are')
    out.append(' * narrow, which is what lets a centred string be centred on its ink')
    out.append(' * rather than on a trailing gap no pixel occupies. */')
    out.append('static const unsigned char font_w[FONT_SLOTS] = {')
    for i in range(0, SLOTS, 16):
        out.append('    ' + ', '.join('%d' % w for w in width[i:i + 16]) + ',')
    out.append('};')
    out.append('')
    out.append('#endif /* FONT_DATA_H */')

    path = os.path.join(ROOT, 'src', 'font.h')
    open(path, 'w').write('\n'.join(out) + '\n')
    print('wrote %s: %d glyphs, %d rows, widths %d..%d, advance %d'
          % (path, sum(1 for w in width if w), ROWS,
             min(w for w in width if w), max(width), advance))


if __name__ == '__main__':
    main()
